#!/usr/bin/env bash
# init-env.sh — generate .env for the macOS/Colima tunnel host on first setup.
# Mints BETTER_AUTH_SECRET + POSTGRES_PASSWORD (openssl) and a VAPID keypair (FATAL on
# failure — push is a real deliverable under HTTPS), prompts for the https APP_URL and the
# Cloudflare TUNNEL_TOKEN, and writes AUTH_TRUSTED_IP_HEADER=cf-connecting-ip,
# AUTH_RATE_LIMIT_MAX=10, APP_PORT=3000. Refuses to clobber an existing .env unless -f/--force.
set -euo pipefail
cd "$(dirname "$0")/../.."
ENV_PATH=".env"

force=0
while [ $# -gt 0 ]; do
  case "$1" in
    -f|--force) force=1 ;;
    *) echo "usage: scripts/macos/init-env.sh [-f|--force]" >&2; exit 2 ;;
  esac
  shift
done
if [ -e "$ENV_PATH" ] && [ "$force" -ne 1 ]; then
  echo ".env already exists at $ENV_PATH — re-run with -f/--force to overwrite." >&2
  exit 1
fi

# --- Secrets (hex: shell-safe, no +,/,=) ---
SECRET=$(openssl rand -hex 32)   # 64 hex chars >= 32 (BETTER_AUTH_SECRET floor)
PGPASS=$(openssl rand -hex 24)   # 48 hex chars
SETUP_TOKEN=$(openssl rand -hex 32)  # F1 one-time bootstrap gate — entered once in the wizard

# --- APP_URL (https, exact scheme+host; trailing slash trimmed so Origin/baseURL match) ---
read -r -p 'APP_URL (public https origin, e.g. https://labhub.example.com): ' APP_URL
APP_URL="${APP_URL%/}"
case "$APP_URL" in
  https://*) : ;;
  *) echo "FATAL: APP_URL must start with https:// (got '$APP_URL'). A mismatch 403s sign-in." >&2; exit 1 ;;
esac

# --- TUNNEL_TOKEN (Cloudflare connector token; opaque) ---
read -r -p 'TUNNEL_TOKEN (Cloudflare Tunnel connector token): ' TUNNEL_TOKEN
[ -n "$TUNNEL_TOKEN" ] || echo "note: TUNNEL_TOKEN left blank — cloudflared will fail until you set it in .env." >&2

# --- VAPID keypair (FATAL on failure — §6.2) ---
mint_vapid() {
  if command -v npx >/dev/null 2>&1; then
    npx -y web-push generate-vapid-keys 2>/dev/null && return 0
  fi
  docker run --rm node:22-alpine sh -c 'npx -y web-push generate-vapid-keys' 2>/dev/null
}
extract_key() { # $1 = label; prints the first non-empty line AFTER the label line
  awk -v lbl="$1" '$0 ~ lbl {found=1; next} found && NF {print; exit}'
}
echo 'Minting a VAPID keypair ...'
VAPID_OUT="$(mint_vapid || true)"
VAPID_PUBLIC="$(printf '%s\n' "$VAPID_OUT" | extract_key 'Public Key:')"
VAPID_PRIVATE="$(printf '%s\n' "$VAPID_OUT" | extract_key 'Private Key:')"
if [ -z "$VAPID_PUBLIC" ] || [ -z "$VAPID_PRIVATE" ]; then
  echo 'FATAL: could not mint VAPID keys. Web Push is a required deliverable under HTTPS.' >&2
  echo 'Ensure Node (npx) or Docker (node:22-alpine) is available, then re-run.' >&2
  exit 1
fi
echo 'VAPID keypair minted.'

# --- Write .env (ASCII, no BOM) ---
cat > "$ENV_PATH" <<EOF
# Generated by scripts/macos/init-env.sh — do NOT commit this file.
DATABASE_URL=postgresql://labhub:${PGPASS}@localhost:5432/labhub
POSTGRES_PASSWORD=${PGPASS}
APP_URL=${APP_URL}
APP_PORT=3000
BETTER_AUTH_SECRET=${SECRET}
UPLOADS_DIR=/data/uploads
# Behind the Cloudflare tunnel CF-Connecting-IP is the single, unspoofable client IP, so the
# per-client sign-in/up limiter works at the code default of 10 (see src/lib/auth-ip.ts).
AUTH_TRUSTED_IP_HEADER=cf-connecting-ip
AUTH_RATE_LIMIT_MAX=10
# One-time bootstrap gate (F1): the setup wizard requires this token before creating the first
# admin, so no un-invited party can seize admin over the public tunnel during provisioning.
SETUP_TOKEN=${SETUP_TOKEN}
# SMTP intentionally blank — invitations use copyable links.
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=LabHub <no-reply@localhost>
VAPID_PUBLIC_KEY=${VAPID_PUBLIC}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE}
TUNNEL_TOKEN=${TUNNEL_TOKEN}
DISABLE_JOBS=
EOF
echo "Wrote $ENV_PATH"
echo ''
echo '=== SETUP TOKEN (enter this once in the setup wizard) ==='
echo "  SETUP_TOKEN=${SETUP_TOKEN}"
echo '  Keep it private. It stops an un-invited party claiming admin over the public tunnel'
echo '  before you finish setup. It is only needed for the one-time wizard.'
echo '========================================================'
echo ''
echo "Next: docker compose --profile prod --profile tunnel up -d --build   (then open $APP_URL)"
