-- AlterTable: additive, nullable per-user theme preference.
-- (Autogenerated drift touching Message.search — a raw FTS generated column
-- not modeled in schema.prisma — has been removed so this migration stays
-- purely additive.)
ALTER TABLE "user" ADD COLUMN     "themePreference" TEXT;
