#requires -Version 5.1
<#
  init-env.ps1 — generate .env from the template on first setup (Windows server).
  Mints BETTER_AUTH_SECRET + POSTGRES_PASSWORD with the .NET crypto RNG (no host
  openssl), prompts for APP_URL, sets APP_PORT (default 80 → clean http://<host>/),
  leaves SMTP blank, and best-effort mints a VAPID keypair in a throwaway node
  container. Push is dormant on plain HTTP anyway, so a VAPID failure only prints a
  note. Refuses to clobber an existing .env unless -Force.
#>
[CmdletBinding()]
param([string]$AppUrl, [int]$AppPort = 80, [switch]$Force)
$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $false
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$envPath = Join-Path $repo '.env'

if ((Test-Path $envPath) -and -not $Force) {
  Write-Host ".env already exists at $envPath. Re-run with -Force to overwrite." -ForegroundColor Yellow
  exit 1
}

function New-Secret([int]$bytes = 32) {
  $b = [byte[]]::new($bytes)
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try { $rng.GetBytes($b) } finally { $rng.Dispose() }
  return -join ($b | ForEach-Object { $_.ToString('x2') })  # hex: shell-safe (no +,/,=)
}

if (-not $AppUrl) { $AppUrl = Read-Host 'APP_URL members will use (e.g. http://colossus-lab/ )' }
$secret = New-Secret 32   # 64 hex chars >= 32 (BETTER_AUTH_SECRET floor)
$pgPass = New-Secret 24   # 48 hex chars

# Best-effort VAPID via a throwaway node container (no Node needed on the host).
$vapidPublic = ''; $vapidPrivate = ''
try {
  Write-Host 'Minting a VAPID keypair (docker run node:22-alpine) ...'
  $text = (docker run --rm node:22-alpine sh -c 'npx -y web-push generate-vapid-keys' 2>$null | Out-String)
  $mPub  = [regex]::Match($text, 'Public Key:\s+([A-Za-z0-9_\-]+)')
  $mPriv = [regex]::Match($text, 'Private Key:\s+([A-Za-z0-9_\-]+)')
  if ($mPub.Success -and $mPriv.Success) {
    $vapidPublic = $mPub.Groups[1].Value; $vapidPrivate = $mPriv.Groups[1].Value
    Write-Host 'VAPID keypair minted.' -ForegroundColor Green
  } else {
    Write-Host 'note: could not parse VAPID keys — leaving blank (push is dormant on http anyway).' -ForegroundColor Yellow
  }
} catch {
  Write-Host 'note: VAPID minting skipped (Docker not ready?) — leaving blank; push is dormant on http.' -ForegroundColor Yellow
}

$lines = @(
  '# Generated by scripts/windows/init-env.ps1 — do NOT commit this file.'
  "DATABASE_URL=postgresql://labhub:$pgPass@localhost:5432/labhub"  # host tooling only; the app container derives its URL from POSTGRES_PASSWORD via compose
  "POSTGRES_PASSWORD=$pgPass"
  "APP_URL=$AppUrl"
  "APP_PORT=$AppPort"
  "BETTER_AUTH_SECRET=$secret"
  'UPLOADS_DIR=/data/uploads'
  '# Shared-IP LAN: the published port SNATs every client to one gateway IP, so the per-IP'
  '# sign-in/up limiter is lab-wide. Raise it so one onboarding burst / fat-fingered password'
  '# does not 429 sign-in for everyone. The limiter stays ON; code default is 10 (dev/CI).'
  'AUTH_RATE_LIMIT_MAX=100'
  '# SMTP intentionally blank on day one — invitations use copyable links.'
  'SMTP_HOST='
  'SMTP_PORT=587'
  'SMTP_USER='
  'SMTP_PASS='
  'SMTP_FROM=LabHub <no-reply@localhost>'
  "VAPID_PUBLIC_KEY=$vapidPublic"
  "VAPID_PRIVATE_KEY=$vapidPrivate"
  'DISABLE_JOBS='
)
Set-Content -LiteralPath $envPath -Value $lines -Encoding ASCII  # no BOM (compose .env must not have one)
Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host "Next: docker compose --profile prod up -d --build   (then open $AppUrl)"
